.\"  Copyright (C) 2014  Yubico AB
.\"
.\"  This program is free software: you can redistribute it and/or modify
.\"  it under the terms of the GNU General Public License as published by
.\"  the Free Software Foundation, either version 3 of the License, or
.\"  (at your option) any later version.
.\"
.\"  This program is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"
.\"  You should have received a copy of the GNU General Public License
.\"  along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" The following commands are required for all man pages.
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH u2f-register "1" "Aug 2013" "python-u2flib-host"
.SH NAME
u2f-register - Command-line tool for registering a U2F device.
.SH SYNOPSIS
.B u2f-register
[\fI--help\fR] [\fI--infile file\fR] [\fI--outfile file\fR] facet

.SH DESCRIPTION
Register a U2F device. Takes a JSON formatted RegisterRequest object on stdin,
and returns the result on stdout.
.HP
\fB\-\-help, \-h\fR Usage help.
.HP
\fB\-\-infile, \-i\fR A file to read registration data from, instead of stdin.
.HP
\fB\-\-outfile, \-o\fR A file to write output to, instead of stdout.
.HP
\fB\-\-soft, \-s\fR A file to use as a soft U2F token. It will be created if
it does not exist.
.HP
\fBfacet \fR The facet of the RegistrationRequest.
.SH BUGS
Report u2f-register bugs in
.URL "https://github.com/Yubico/python-u2flib-host/issues" "the issue tracker"
